version: '3.7'

services:
  osticket:
    image: campbellsoftwaresolutions/osticket
    container_name: osticket
    depends_on:
      - mariadb
    volumes:
      - osticket_app:/var/www/html
    environment:
      INSTALL_SECRET: "MySecretKey123"
      MYSQL_HOST: mariadb
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticket123
      MYSQL_DATABASE: osticket

  mariadb:
    image: mariadb:10.5
    container_name: osticket-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticket123
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx:stable
    container_name: osticket-nginx
    depends_on:
      - osticket
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: osticket-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot

volumes:
  osticket_app:
  mariadb_data:
